Import('env')
Import('deps')

env = env.Clone()

src = [
    File('main.cc'),
    File('host_pcie.cc'),
    File('target_pcie.cc'),
    File('conv_accel.cc'),
]

bin = env.Program('gem5.sc', src + deps)

Return('bin')